name: reusable-test-container

on:
    workflow_call:
      inputs:
        container_name:
          description: "Name of the container (e.g., fedora, ubi9)"
          required: true
          type: string

jobs:
  shared-config:
    name: Shared configuration
    runs-on: ubuntu-latest
    outputs:
      base_image: ${{ steps.config.outputs.base_image }}
      base_version: ${{ steps.config.outputs.base_version }}
      bootc_image: ${{ steps.config.outputs.bootc_image }}
      release_tag: ${{ steps.release.outputs.tag }}
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2

      - name: Fetch container configuration and use output
        id: config
        uses: gbraad-actions/shared-config@main
        with:
          config_file: containers/gbraad-dotfiles/upstream/${{ inputs.container_name }}.ini
          use_output: true

  test-arm64:
    needs: shared-config
    name: Test ARM64
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Test pull image
        run: |
          podman pull ${{ needs.shared-config.outputs.base_image }}:${{ needs.shared-config.outputs.base_version }}

  test-amd64:
    needs: shared-config
    name: Test AMD64
    runs-on: ubuntu-24.04
    steps:
      - name: Test pull image
        run: |
          podman pull ${{ needs.shared-config.outputs.base_image }}:${{ needs.shared-config.outputs.base_version }}
