name: Test UBI9 container

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
  pull_request: {}


jobs:
  test:
    name: Test pull - UBI9
    uses: ./.github/workflows/reusable-test-container.yml
    with:
      container_name: "ubi9"
    secrets: inherit
