name: Test Debian container

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
  pull_request: {}


jobs:
  test:
    name: Test pull - Debian
    uses: ./.github/workflows/reusable-test-container.yml
    with:
      container_name: "debian"
    secrets: inherit
